#!/bin/sh

system_type=$(uname -s)

##################################
#   Global

# install node if it's missing
if ! command -v node >/dev/null 2>&1; then
    echo "Install latest Nodejs lts"
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
fi

echo "Updating the yadm repo origin URL"
yadm remote set-url origin "git@github.com:techie2000/dotfiles-yadm.git"

#################################
#    Darwin
if [ "$system_type" = "Darwin" ]; then

    # install homebrew if it's missing
    if ! command -v brew >/dev/null 2>&1; then
        echo "Installing homebrew"
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    fi

    if [ -f "$HOME/Brewfile" ]; then
        echo "Updating homebrew bundle"
        brew bundle --global
    fi

fi
