#!/bin/bash

# Stop on any error
set -o errexit

##################################
#   Global

source "$HOME/.config/yadm/bootstrap.d/000_core/200_functions"

print_script_name

cleanup_home
#update_yadm_repo
cleanup_tmp
print_footer
