#!/bin/bash 

if [ -f /etc/bash_completion.d/git ]; then
    source /etc/bash_completion.d/git
fi

if [ -f /etc/bash_completion.d/git5 ]; then
    source /etc/bash_completion.d/git5
fi

if command -v git >/dev/null 2>&1; then
    alias   ga='gad'
    alias  gad='git add '
    alias  gbr='git branch '
    alias  gco='git commit'
    alias   gc='gco'
    alias   gd='gdi'
    alias  gdi='git diff'
    alias  gch='git checkout '
    alias gita='gad'
    alias gitc='gco'
    alias gitd='gdi'
    alias gitp='gpu'
    alias gits='gst'
    alias   gp='gpu'
    alias  gpu='git pull'
    alias   gs='gst'
    alias  gst='git status'
    alias  got='git '          # typos
    alias  gut='git '          # typos
fi

