#!/bin/bash

# Stop on any error
set -o errexit

source "$HOME/.config/yadm/bootstrap.d/000_core/200_functions"

print_script_name

##################################
#   install_thefuck()

# Only used on Debian/Ubuntu based distributions.
install_thefuck() {

    info "Current function: ${FUNCNAME[1]}"

    info "Installing thefuck using pip..."
    sudo apt install --yes python3-dev python3-pip python3-setuptools
    pip3 install thefuck --user
}
