#!/bin/bash

# Stop on any error
set -o errexit

##################################
#   Linux Packages List

source "$HOME/.config/yadm/bootstrap.d/000_core/200_functions"

print_script_name

# gnu-standards libtool gettext m4-doc ncurses-doc
linux_pkg_list=(
    "apt-transport-https"
    "autoconf"
    "autoconf-archive"
    "autotools-dev"
    "autoconf-doc"
    "build-essential"
    "bzip2"
    "ca-certificates"
    "cargo"
    "cargo-doc"
    "command-not-found"
    "curl"
    "deborphan"
    "duf"
    "exiftool"
    "flatpak"
    "fzf"
    "gcc"
    "git"
    "gnupg"
    "gpg"
    "gzip"
    "highlight"              # Optional dependency for 'ranger'.
    "htop"
    "iftop"
    "imagemagick"
    "inetutils-traceroute"
    "iotop"
    "jsonnet"
    "jq"
    "libcairo2-dev"
    "libcups2-dev"
    "libdbus-1-dev"
    "libgirepository1.0-dev"
     "libglib2.0-dev"
    "libncurses5-dev"
    "libssl-dev"
    "libsystemd-dev"
    "lm-sensors"
    "lsb-release"
    "make"
    "mc"
    "mediainfo"
    "nano"
    "node-js-beautify"
    "nq"
    "openssh-client"
    "openssh-server"
    "postgresql"
    "postgresql-client"
    "postgresql-client-common"
    "postgresql-contrib"
    "postgresql-doc"
    "postgresql-doc-14"
    "p7zip-full"
    "p7zip-rar"
    "perl"
    "python3"
    "python3-pip"
    "qemu-guest-agent"
    "ranger"
    "shellcheck"
    "tidy"
    "thefuck"
    "tree"
    "unrar"
    "unzip"
    "vim"
    "vim-doc"
    "w3m"                    # Optional dependency for 'ranger'.
    "wget"
    "yamllint"
    "zip"
    "zlib1g-dev"
    "zsh"
    "zsh-doc"
)

if (( WSL )); then
  linux_pkg_list+=(
  dbus-x11
  gnome-icon-theme
  x11-utils
  )
fi
