#!/bin/bash

# Stop on any error
set -o errexit

##################################
#   Cargo Tools List

source "$HOME/.config/yadm/bootstrap.d/000_core/200_functions"

print_script_name

cargo_tools_list=(
    "ripgrep"
    "fd-find"
    "exa"
    "bat"
    "zoxide"
    "difftastic"
)
