#!/bin/bash

# Stop on any error
set -o errexit

##################################
#   Linux Packages List

source "$HOME/.config/yadm/bootstrap.d/000_core/200_functions"

print_script_name

linux_pkg_list=(
    "cargo"
    "curl"
    "duf"
    "flatpak"
    "git"
    "highlight"              # Optional dependency for 'ranger'.
    "htop"
    "iftop"
    "iotop"
    "mc"
    "node-js-beautify"
    "nq"
    "postgresql"
    "postgresql-client"
    "postgresql-client-common"
    "postgresql-contrib"
    "ranger"
    "tidy"
    "thefuck"
    "tree"
    "unzip"
    "vim"
    "w3m"                    # Optional dependency for 'ranger'.
    "yamllint"
    "zsh"
)
